### ISSUE TITLE
NIMBLE runtime

### ISSUE THREAD

**Issue by KaiZhuPhD** [cboettig/nimbios-transients#11]
@henryrscharf How long did it take for you to run `code/scharf_nimble/fit.R`? My NIMBLE simulation is very slow, taking hours still can't finish, even on an HPC server.

**Comment by henryrscharf** [comment]
@KaiZhuPhD For n = 100, it took several hours to run `fit.R` on my machine, but n = 1 or 10 are more reasonable.
